version: '4.0'

services:
  api-brecho:
    image: bitnami/postgresql
    container_name: databasebrecho
    restart: always
    environment:
      POSTGRESQL_DATABASE: 'brecho'   
      POSTGRESQL_USER: 'docker'
      POSTGRESQL_PASSWORD: 'docker@'      
      POSTGRESQL_POSTGRES_PASSWORD: 'docker@'
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/bitnami/postgresql
    user: root

  app:
    build: .
    container_name: brecho-app
    depends_on:
      - api-brecho
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgres://docker:docker@@api-brecho:5432/brecho
    volumes:
      - .:/app